# Generated by Django 3.2.3 on 2021-06-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210613_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alignment',
            name='image1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alignment',
            name='image2',
            field=models.URLField(blank=True, null=True),
        ),
    ]
