# Generated by Django 3.2.3 on 2021-06-14 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20210613_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alignment',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='alignment',
            name='image2',
        ),
        migrations.AddField(
            model_name='alignment',
            name='image',
            field=models.TextField(null=True),
        ),
    ]
